"""add_chunk_relationships_and_offsets

Revision ID: 37050275ff76
Revises: 194eb1375de8
Create Date: 2026-05-22 16:24:05.105842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37050275ff76'
down_revision: Union[str, Sequence[str], None] = '194eb1375de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunk_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=False),
    sa.Column('target_chunk_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document_chunks', sa.Column('char_start', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('char_end', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('sha256', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_column('documents', 'sha256')
    op.drop_column('document_chunks', 'char_end')
    op.drop_column('document_chunks', 'char_start')
    op.drop_table('document_chunk_relationships')
    # ### end Alembic commands ###
